set(CMAKE_SYSTEM_NAME Generic-ELF)

find_program(TRICORE_GCC tricore-gcc)
set(CMAKE_C_COMPILER ${TRICORE_GCC})

set(CMAKE_C_FLAGS_INIT "-mcpu=tc39xx")
set(CMAKE_EXE_LINKER_FLAGS "-mcpu=tc39xx")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
