set(CMAKE_SYSTEM_NAME Generic-ELF)
set(CMAKE_TASKING_TOOLSET TriCore)
set(CMAKE_SYSTEM_PROCESSOR TriCore)

find_program(TASKING_COMPILER cctc)
set(CMAKE_C_COMPILER ${TASKING_COMPILER})

set(CMAKE_C_FLAGS_INIT "--cpu=tc39x")
#set(CMAKE_EXE_LINKER_FLAGS "--lsl-file=tc39x.lsl -Wl-DRESET=0xa0000000 -Wl--output=:ihex")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
